
BEGIN
  FOR t IN (SELECT table_name FROM user_tables
            WHERE table_name IN ('EVM_HISTORY','METRICS','TASKS',
                                 'SPRINTS','PROJECTS','USERS','ROLES'))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

CREATE TABLE Roles (
    role_id   INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR2(60)  NOT NULL,
    CONSTRAINT uq_role_name UNIQUE (role_name)   -- prevent duplicate role names
);

CREATE TABLE Users (
    user_id       INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role_id       INT,
    CONSTRAINT uq_username     UNIQUE (username),
    CONSTRAINT fk_user_role    FOREIGN KEY (role_id) REFERENCES Roles(role_id)
                               ON DELETE SET NULL,
    CONSTRAINT chk_pwd_length  CHECK (LENGTH(password_hash) >= 8)
);


CREATE TABLE Projects (
    project_id   INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR2(150)  NOT NULL,
    total_budget NUMBER(15, 2)  DEFAULT 0 NOT NULL,
    start_date   DATE,
    end_date     DATE,
    manager_id   INT,
    CONSTRAINT fk_project_manager FOREIGN KEY (manager_id) REFERENCES Users(user_id)
                                  ON DELETE SET NULL,
    CONSTRAINT chk_project_dates  CHECK (end_date IS NULL OR start_date IS NULL
                                         OR end_date >= start_date),
    CONSTRAINT chk_budget_positive CHECK (total_budget >= 0)
);

CREATE TABLE Sprints (
    sprint_id    INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   INT            NOT NULL,
    sprint_no    INT            NOT NULL,
    sprint_name  VARCHAR2(100),
    start_date   DATE,
    end_date     DATE,
    planned_value NUMBER(12, 2) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_sprint_project   FOREIGN KEY (project_id) REFERENCES Projects(project_id)
                                   ON DELETE CASCADE,
    CONSTRAINT uq_sprint_per_proj  UNIQUE (project_id, sprint_no),           -- no dup sprint numbers
    CONSTRAINT chk_sprint_dates    CHECK (end_date IS NULL OR start_date IS NULL
                                          OR end_date >= start_date),
    CONSTRAINT chk_pv_positive     CHECK (planned_value >= 0)
);
CREATE TABLE Tasks (
    task_id          INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sprint_id        INT            NOT NULL,
    assigned_to      INT,
    external_id      VARCHAR2(50),                   -- JIRA ticket / GitHub issue ref
    task_description VARCHAR2(500),
    status           VARCHAR2(20)   DEFAULT 'To Do'  NOT NULL,
    story_points     INT            DEFAULT 0        NOT NULL,
    CONSTRAINT fk_task_sprint    FOREIGN KEY (sprint_id)   REFERENCES Sprints(sprint_id)
                                 ON DELETE CASCADE,
    CONSTRAINT fk_task_dev       FOREIGN KEY (assigned_to) REFERENCES Users(user_id)
                                 ON DELETE SET NULL,
    CONSTRAINT chk_task_status   CHECK (status IN ('To Do', 'In Progress', 'Done')),
    CONSTRAINT chk_story_points  CHECK (story_points >= 0)
);


CREATE TABLE Metrics (
    metric_id        INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id          INT            NOT NULL,
    tester_id        INT,
    critical_bugs    INT            DEFAULT 0  NOT NULL,
    major_bugs       INT            DEFAULT 0  NOT NULL,
    minor_bugs       INT            DEFAULT 0  NOT NULL,
    bug_count        INT            DEFAULT 0  NOT NULL,   -- auto-computed via trigger
    code_coverage    NUMBER(5, 2)   DEFAULT 0,
    tech_debt_hours  NUMBER(10, 2)  DEFAULT 0,
    calculated_qpi   NUMBER(5, 2)   DEFAULT 100.00,
    CONSTRAINT fk_metric_task      FOREIGN KEY (task_id)   REFERENCES Tasks(task_id)
                                   ON DELETE CASCADE,
    CONSTRAINT fk_metric_tester    FOREIGN KEY (tester_id) REFERENCES Users(user_id)
                                   ON DELETE SET NULL,
    CONSTRAINT uq_metric_task      UNIQUE (task_id),       -- one metric record per task
    CONSTRAINT chk_bugs_nn         CHECK (critical_bugs >= 0 AND major_bugs >= 0 AND minor_bugs >= 0),
    CONSTRAINT chk_coverage_range  CHECK (code_coverage BETWEEN 0 AND 100),
    CONSTRAINT chk_qpi_range       CHECK (calculated_qpi BETWEEN 0 AND 100)
);


CREATE TABLE EVM_History (
    history_id                INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id                INT            NOT NULL,
    snapshot_date             TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total_pv                  NUMBER(15, 2)  DEFAULT 0,
    total_ev                  NUMBER(15, 2)  DEFAULT 0,
    total_ac                  NUMBER(15, 2)  DEFAULT 0,
    cpi                       NUMBER(5, 2),
    spi                       NUMBER(5, 2),
    qpi                       NUMBER(5, 2),
    ai_prediction_eac         NUMBER(15, 2),
    ai_variance_at_completion NUMBER(15, 2),
    CONSTRAINT fk_history_project  FOREIGN KEY (project_id) REFERENCES Projects(project_id)
                                   ON DELETE CASCADE,
    CONSTRAINT chk_history_pv_nn   CHECK (total_pv >= 0),
    CONSTRAINT chk_history_ev_nn   CHECK (total_ev >= 0)
);



CREATE INDEX idx_projects_manager   ON Projects(manager_id);
CREATE INDEX idx_sprints_project    ON Sprints(project_id);
CREATE INDEX idx_tasks_sprint       ON Tasks(sprint_id);
CREATE INDEX idx_tasks_assigned     ON Tasks(assigned_to);
CREATE INDEX idx_metrics_task       ON Metrics(task_id);
CREATE INDEX idx_evm_project        ON EVM_History(project_id);

CREATE INDEX idx_tasks_status       ON Tasks(status);               -- filter by Done/In Progress/To Do
CREATE INDEX idx_evm_snapshot_date  ON EVM_History(snapshot_date);  -- time-series queries
CREATE INDEX idx_sprints_start_date ON Sprints(start_date);         -- AC calculation (started sprints)
CREATE INDEX idx_metrics_qpi        ON Metrics(calculated_qpi);     -- QPI analytics
CREATE INDEX idx_tasks_ext_id       ON Tasks(external_id);          -- JIRA/GitHub lookups

CREATE OR REPLACE TRIGGER trg_metrics_bug_count
BEFORE INSERT OR UPDATE ON Metrics
FOR EACH ROW
BEGIN
    :NEW.bug_count := NVL(:NEW.critical_bugs, 0)
                    + NVL(:NEW.major_bugs, 0)
                    + NVL(:NEW.minor_bugs, 0);
END;
/


CREATE OR REPLACE TRIGGER trg_sprint_no_unique
BEFORE INSERT OR UPDATE ON Sprints
FOR EACH ROW
DECLARE
    v_count INT;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM Sprints
    WHERE project_id = :NEW.project_id
      AND sprint_no  = :NEW.sprint_no
      AND sprint_id <> NVL(:NEW.sprint_id, -1);

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'Sprint number ' || :NEW.sprint_no ||
            ' already exists for project ' || :NEW.project_id);
    END IF;
END;
/



CREATE OR REPLACE VIEW vw_real_time_dashboard AS
SELECT
    p.project_id,
    p.project_name,
    p.total_budget,
    u.username                                                         AS manager_name,
    p.start_date,
    p.end_date,
    COUNT(DISTINCT s.sprint_id)                                        AS sprint_count,
    COUNT(DISTINCT t.task_id)                                          AS total_tasks,
    COUNT(DISTINCT CASE WHEN t.status = 'Done' THEN t.task_id END)    AS done_tasks,
    SUM(s.planned_value)                                               AS total_pv,
    SUM(CASE WHEN t.status = 'Done'
             THEN t.story_points * 100 ELSE 0 END)                    AS total_ev,
    SUM(CASE WHEN s.start_date IS NOT NULL
             THEN s.planned_value ELSE 0 END)                         AS total_ac,
    ROUND(
        SUM(CASE WHEN t.status = 'Done' THEN t.story_points * 100 ELSE 0 END) /
        NULLIF(SUM(CASE WHEN s.start_date IS NOT NULL THEN s.planned_value ELSE 0 END), 0),
    2)                                                                 AS cpi,
    ROUND(
        SUM(CASE WHEN t.status = 'Done' THEN t.story_points * 100 ELSE 0 END) /
        NULLIF(SUM(s.planned_value), 0),
    2)                                                                 AS spi,
    ROUND(AVG(m.calculated_qpi), 2)                                   AS avg_qpi,
    CASE
        WHEN ROUND(SUM(CASE WHEN t.status = 'Done' THEN t.story_points * 100 ELSE 0 END) /
             NULLIF(SUM(CASE WHEN s.start_date IS NOT NULL THEN s.planned_value ELSE 0 END), 0), 2) >= 1.0
         AND ROUND(SUM(CASE WHEN t.status = 'Done' THEN t.story_points * 100 ELSE 0 END) /
             NULLIF(SUM(s.planned_value), 0), 2) >= 1.0
        THEN 'Green - On track'
        WHEN ROUND(SUM(CASE WHEN t.status = 'Done' THEN t.story_points * 100 ELSE 0 END) /
             NULLIF(SUM(CASE WHEN s.start_date IS NOT NULL THEN s.planned_value ELSE 0 END), 0), 2) >= 0.8
         AND ROUND(SUM(CASE WHEN t.status = 'Done' THEN t.story_points * 100 ELSE 0 END) /
             NULLIF(SUM(s.planned_value), 0), 2) >= 0.8
        THEN 'Yellow - At risk'
        ELSE 'Red - Off track'
    END                                                                AS health_status
FROM Projects p
LEFT JOIN Users   u ON p.manager_id  = u.user_id
LEFT JOIN Sprints s ON p.project_id  = s.project_id
LEFT JOIN Tasks   t ON s.sprint_id   = t.sprint_id
LEFT JOIN Metrics m ON t.task_id     = m.task_id
GROUP BY p.project_id, p.project_name, p.total_budget,
         u.username, p.start_date, p.end_date;

-- View 2: Portfolio-level aggregation
CREATE OR REPLACE VIEW vw_multi_project_portfolio AS
SELECT
    COUNT(*)                 AS total_projects,
    ROUND(AVG(cpi), 2)       AS portfolio_cpi,
    ROUND(AVG(spi), 2)       AS portfolio_spi,
    ROUND(AVG(avg_qpi), 2)   AS portfolio_qpi,
    SUM(total_budget)        AS total_portfolio_budget,
    SUM(total_pv)            AS total_portfolio_pv,
    SUM(total_ev)            AS total_portfolio_ev,
    COUNT(CASE WHEN health_status = 'Green - On track'  THEN 1 END) AS green_projects,
    COUNT(CASE WHEN health_status = 'Yellow - At risk'  THEN 1 END) AS yellow_projects,
    COUNT(CASE WHEN health_status = 'Red - Off track'   THEN 1 END) AS red_projects
FROM vw_real_time_dashboard;

-- View 3: Developer workload view
CREATE OR REPLACE VIEW vw_developer_workload AS
SELECT
    u.user_id,
    u.username,
    COUNT(t.task_id)                                                AS total_tasks,
    COUNT(CASE WHEN t.status = 'Done'        THEN 1 END)           AS done_tasks,
    COUNT(CASE WHEN t.status = 'In Progress' THEN 1 END)           AS in_progress_tasks,
    COUNT(CASE WHEN t.status = 'To Do'       THEN 1 END)           AS todo_tasks,
    SUM(t.story_points)                                             AS total_story_points,
    ROUND(AVG(m.calculated_qpi), 2)                                AS avg_qpi,
    ROUND(AVG(m.code_coverage), 2)                                 AS avg_coverage
FROM Users u
LEFT JOIN Tasks   t ON u.user_id = t.assigned_to
LEFT JOIN Metrics m ON t.task_id = m.task_id
GROUP BY u.user_id, u.username;





GRANT SELECT ON Roles    TO PUBLIC;
GRANT SELECT ON Projects TO PUBLIC;
GRANT SELECT ON Sprints  TO PUBLIC;
GRANT SELECT ON Tasks    TO PUBLIC;

CREATE OR REPLACE VIEW vw_admin_full AS
SELECT
    p.project_id, p.project_name, p.total_budget,
    p.start_date, p.end_date,
    u.username AS manager_name,
    r.role_name
FROM Projects p
LEFT JOIN Users u ON p.manager_id = u.user_id
LEFT JOIN Roles r ON u.role_id    = r.role_id;


CREATE OR REPLACE VIEW vw_pm_projects AS
SELECT * FROM Projects
WHERE manager_id = (SELECT user_id FROM Users WHERE username = USER);


CREATE OR REPLACE VIEW vw_team_tasks AS
SELECT t.* FROM Tasks t
WHERE t.assigned_to = (SELECT user_id FROM Users WHERE username = USER);
